<%@ Page Title="" Language="C#" MasterPageFile="~/Default.master" AutoEventWireup="true" CodeBehind="Article12.aspx.cs" Inherits="ProfessorTesting.Fragments.Article12" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadPH" runat="server">
    <style type="text/css">
        .main td, th {border:1px solid black;padding:.5em}
        .main table {border-collapse:collapse}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div class="main noselect" onmousedown="return false;" onclick="return true;" oncopy="return false;">
        <div style="margin-left:30px;margin-right:30px">
<h2>Psychoeconomical Crisis of Today:  Analogues in the Past...</h2>
<p>This article contains reflections of psychologists оn causes of the world economic crisis (see 2). The core of the expressed conception consists in that the cycling of socio-economic development is associated with the cycling of psychotype change in humans and with the cycling of solar activity.  Coincidence of hegemony of the third generation elite with enrichment of hysteroidity traits in the economically active population gives rise to psychoeconomical crises of abnormal depth. The world passed through this from 1929 to 1939, we are passing through this now (from 2008). Before, overcoming the crisis of this kind was possible through wars, revolutions, famine etc forcedly changing the people. The degree of these commotions may be reduced by understanding of psychoeconomic grounds of such crises.</p>
<h3>Initial psychological terms.</h3>
<p><b>Hysteroid accentuation</b> - an accentuation type, when a person at a level of dynamic stereotypes is highly emotional, sensitive, “winded up”, likes to be compelling and can not do without this. In the course of practical work, in order to attract  attention,  can act the way that the other people won’t act (suggest an idea now, then suddenly swear at somebody, compliment now, then disagree to something and in the presence of everybody complain to Senior officer etc). And these acts are dictated not by core of a problem, but rather by unconscious wish to hold the attention. Hysteroid type of accentuations or demonstrative one – solicitous of attention, recognition of entourage by all accessible means.</p>
<p><b>Paranoic accentuation</b> - a psycho-type of a person, who is characterised by seeking to a goal significant to the given personality, to the prejudice of neighborhood sometimes. To such persons, typical are difficulties in overcoming arisen strong emotional reactions, stability, persistence, single-mindedness, presence of resistant attitude to reaching a goal (sometimes, in spite of any arguments) up to generation of predominant ideas or relations. The most leading supervisors are paranoically accentuated. Thus, their predominant idea is a set up business, work. Paranoic or “sticking” type of accentuations – hung up on something under the influence of a “predominant” idea.</p>
<p><b>Reasoning psychotype</b> - one of the main psychotypes of economically active population, which ensure success of society and people in the given historical epoch, in the given activity types, in  the given specific situation… Most often, these are domain experts, with paranoic traits in many cases.</p>
<p><b>Postreasoning psychotype</b> - a type of people, who replace reasoning psychotype, learn from them. More often, these are voluntary helpers, with maniac traits in many cases. It is more often sociablepersonality.</p>
<p><b>Postpostreasoning psychotype</b> - a psychotype, which psychologically and logically succeeds to the postreasoning psychotype . More often, these are, voluntary helpers, with hysteroid traits in many cases.  It is more often lessworkabletype, emotional personality.</p>
<p><b>Domain Expert Metaprogramme</b> - a strategy of need satisfaction by a man, specified by presence of relevant dynamic stereotypes, using industrial process analysis and control, using personal vigilance in the activity, the goal of which is objective (image, object, process etc).  It is more often workabletype of personality.</p>
<p><b>Socialabletype</b> – a strategy of need satisfaction by a man, specified by presence of relevant dynamic stereotypes, using analysis and control of other people, using personal vigilance, activity in the system of interpersonal relations, the goal of which is associated with formation of a required motivation, required behavior of other people.</p>
<p>Influenced by social and natural factors, including the solar activity also, people change.  During some solar activity peaks the people become highly excited, particularly emotional, their hysteroidity and psychopatic state do aggravate.</p>
<p><b>All</b> Russian revolutions (in 1905, 1917 and 1991) coincided with solar activity peaks, the highest ones for decades.</p>
<table>
    <thead>
        <tr><th>Revolutions</th><th>Wolf average per year</th><th>There was no such minimum before revolution</th><th>There was no such maximum after revolution</th><th>The most intense solar radiation for</th></tr>
    </thead>
    <tbody>
        <tr><td>1905</td><td>63,5</td><td>Since 1895</td><td>Before 1916</td><td>22 years</td></tr>
        <tr><td>1917</td><td>104</td><td>Since 1871 (the Commune)</td><td>Before 1937 (Mass repressive measures in Russia)</td><td>66 years</td></tr>
        <tr><td>1991</td><td>1991 – 145,7<br />1990 – 142,6<br />1989 – 157,6<br />for three years on end</td><td>Since 1979 (dropped into in the war in Afghanistan)</td><td>NA so far</td><td>More than for 30 years so far</td></tr>
    </tbody>
</table>
<p>During the quiet sun years the number of such spots is small — 10- 20.</p>
<p>Peaks of solar activity are these ones of social protests and revolutions. Social roles, which had been accepted in the society heretofore (stable social dynamic stereotypes), were removed. The society was ready to accept new roles, begin to live according to new customs, traditions and laws. In terms of physiology of the higher nervous activity, the mechanism of nervous reflex make-and-brake more yielded to change, than in usual conditions.</p>
<p>People are capable to behave, change their dynamic stereotypes in much higher degree, than usually. Influence of hysteroids, psychopathic individuals become automatically stronger, more significant. They have higher  sociometric ratings, exert more efficient influence on neighbourhood, than in usual conditions. Revolution to the hysteroids, who take part in it, in many cases become the time of their fullest emotional satisfaction – on barricades, in the center of attention, everything on a single emotional impulse … Actors on stage of theaters do not experience such emotional outburst.</p>
<p>It may be argued that not all peaks of solar activity resulted in revolutions. That's the case. There are few solar activity peaks, which in Russia did not result in a revolution. In this respect there are two exceptions – 1991 (bringing of troops in Afghanistan) and 1957–1958. The bringing of troops in Afghanistan transferred people excitement, higher psychopathic state to the emotions of “doing internationalist duty”. Though the decision itself was impulsive in many ways.</p>
<p>However, the period from 1957 to 1958 is worthy of an isolated analysis.  The atypical behaviour of the Soviet people should be explained also by that after the war everybody got used to obey and strict dynamic stereotypes of taking dictations and obeying orders of authorities have been developed, whilst simultaneously (!) the mechanism of nervous reflex make-and-brake began to work more actively. This suffices up to 20 years in order to obey less to the influence of the Sun. That’s on the one side.</p>
<p>On the other side, the influence of the country’s leadership on people has emotionalized. The people got emotionalized. The accumulated psychopathic energy found expression in emotions with regard to Stalin cult’s revelation, sputnik’s launch, World Youth Festival, construction of new apartment houses called “khrushchevkas” etc. “Steam got out” due to these and other events.</p>
<p>The rates of economic growth (Kondratiev curve) have relation to the solar activity.</p>
<p>Since 1980, amidst 12 solar activity peaks in 8 cases after passing the peak of solar activity there was an economy growth recession.  Thus, at each stage of Kondratyev cycle growth the peak of solar activity came before the peak achievement.</p>
<p>Economically active population becomes highly emotional one day, then gets to normal state another day. When it’s in normal sate, the economic laws discovered by science apply. In the psychopathic state of population, economic activity subjects, they are deformed depending on a degree of psychopathization of both economically active population and elite.</p>
<p>Wave-like change of human psychotypes, economically active population is superimposed on this one of elite quality. In the countries developing under the influence of internal causes, i.e. depending less than the other ones on influence of neighbouring countries and external factors, the elite’s quality changes radically within three generations.  Surveys of F.Brodel and other researches show that this happened so in the world over a period of thousands of years.</p>
<p>Psychotypes of elite and economically active population are multisided. Let’s look at  only one side — “domain experts”-“voluntary helpers” proportion. People think using metaprogrammes.</p>
<p>“Voluntary helper” is oriented to other people’s opinion, and “domain expert” when taking decision is oriented to technological processes, which he seeks to control.</p>
<p>“Voluntary helpers” are targeted at the system of interpersonal relations, monitor it and via control of this system of relations provide to themselves a real power, making a profit, arrival to prosperity. They get such power by way of formation of their capability to interact with other people and by way of controlling them.</p>
<p>In the history, role and significance of domain experts and voluntary helpers altered fluctuatingly.</p>
<p>In this respect there is a survey of Van Houtte, who states a pendular moving of industry between the cities, boroughs and villages across all the Netherlands since the Middle Ages to 18th century. At first, the industry in the Netherlands was spread across villages. In 18-19th centuries it began to migrate to towns. After a long depression of 1350–1450 the village was again invaded by craftsmen. Workshop organization did not satisfy them anymore. And hired labour in the city also became more expensive. But then in the workshops, the leading position in their management  began to be taken primarily by “voluntary helpers”, persons, who could rally people, make them donate together to common goals.</p>
<p>In the 16-th century, according to the data of Van Houtte’s study, cities became again attractive to the Dutch craftsmen, and in the 17-th century the village re-attracted them. Van Houtte explains this migration by the size of taxes. But the taxes are introduced more often by “voluntary helpers’, and not by «domain experts».</p>
<p>This is generally indicative for any spontaneous people formations and associations. With time, the real democracy is replaced with the rule of “voluntary helpers”. Step by step, this rule leads to oppression of “domain experts” and then to conflicts with them also. Without a certain number of “domain experts”, “voluntary helpers” have nothing to do and no-one to exploit. They are forced to create conditions, which will re-attract “domain experts’ to them.</p>
<p>And such vibrational coupling of “voluntary helpers” and “domain experts” in general contributed to more rapid development of society. That’s enough clear: in such a way compromise conditions of coexistence of “domain experts” and “voluntary helpers”, optimum social and economic structure of society were developed. In the Netherlands such vibrational moving of craftsmen contributed in general to the increase in labour productivity and development of production relations. This correlates with intensive development of Holland in these years.</p>
<p>The basis of a change of key centers of economical development is formed also by “domain experts”- “voluntary helpers” proportion in leadership and by their vibrational succession. So, in the Middle Ages Genoa and Venice competed in the system of economic relations. Loss of leading positions of these city-states often was associated with the rise of a voluntary helpers’ group to power in one of them. Usually, the “voluntary helpers” come under the cloak of democracy. The period of intensive development of democracy is the period of a special activity of “voluntary helpers”. But then the “voluntary helpers” should either lose their power under pressure of masses, or give it to the “domain experts”.</p>
<p>The first generation elite is domain-specific. The second generation elite is packed with voluntary helpers. The third generation elite, without the difficulties, which temper it, without struggle for its domination, without renewal, becomes emotionalized, hysteroid and lose its ability to control the society efficiently.</p>
<p>Such logic of elite formation is correct when the society develops quite conflict-free. At the same time, internal and external conflicts, problems may bring many nuances in this development, up to creation of required conditions for a quick renewal of elite, nomination of clever and able people to be elite, its renewal or quick trends to formation of required capabilities in the existing elite.</p>
<p>Combination of elite type and economically active population type in the country determines  basic socio-economic processes. Thereon hang rates of economic growth,   character of relationship between the various social groups, political processes etc.  In the very unfavourable combination — the third generation elite and state of population, when it imitates emotionalized and psychopathic persons, a psychoeconomical crisis breaks out.</p>
<p>The history shows that the effect of three generations has temporary limits. It may lasts up to 100 years and more, it may last less than 50 years.  And this depends not only on average duration of life (under other equal conditions with the increase of life duration the life time of three generations increases at the average as well). This depends also on social factors, solar activity, managerial decisions taken, person having a determining influence on social and economical processes, decisions of governments, legislative bodies of leading countries of the world, system of external causes.   The USA is the country, external factor impact on the development of which is much lower,  than in most other countries. And here, this lapse of time is more indicative.</p>
<p>The strongest socioeconomic commotion in the US history (it coincided with the peak of solar activity) was the War of Secession in 1861-1865.  As a result, the first generation elite formed.</p>
<p>Heretofore, the first generation elite formed during G.Washington’s ministry (1789-1797). From the date of the beginning of G.Washington’s ministry to the date of outbreak of the War of Secession in the USA passed 72 years.</p>
<p>As a result of the War of Secession, the first generation elite was formed again.</p>
<p>This elite grew from a struggle, from a violent civil war. The more capable, but not the more sophisticated and successful in the system of interpersonal relations were pushed to the top of social hierarchy.  From the date of outbreak the War of Secession in the USA to the date of termination of the second strongest socioeconomic conflict (crisis of 1929-1933) passed 72 years.  We may count from the date of termination of the War of Secession in the USA. Then we will get 1937. This year was also critical for the US according to economists of today.   If we add 72 years to 1937, we will get 2009.  Though it is commonly supposed that the world crisis began in 2008, even so this coincidence of figures has a sacral nature.</p>
<p>In the period of wars the succession of psychotypes of elite, economically active population, the country development is subject to some other objective laws.</p>
<p>New elite of the first generation in the USA grew also during the war. Let’s add 72 years to 1945 (or to 1944 — UNMFC)  . 2017 (plus or minus 3 years) –  this is time period, when by analogy to the past, quite solid grounds may appear to replace the current US elite with a new cohort of persons. But much depends on  the development of the commenced crisis and managerial decisions taken.</p>
<p>These estmations may be disputable.  The depression, crisis of 1873-1896 may be included therein. It may be contested by the fact that different countries have their internal cycles of psychoeconomical crises and the given depression is an example of the influence of Germany (which was in another cycle) on the USA and other countries. This is a scientific dispute. It is important to us that the countries, which less than the other ones depend in their development on influence of neighbouring countries, have the more stable cycle in their development — 3 generations of elite and 2-3 generations of economically active population. This concerned all former world economic centers (Genoa, Antwerp, Amsterdam etc.). This concerned the development of such countries as the USA, USSR, i.e. those countries, which depended less than others on external factors.</p>
<p>One may insist on that one has to count from the date of termination of an event indicative of the rule’s transition from one elite type to another. One may and one need to insist on that the wars deform the process. All this is so. In support of the said above it is quite interesting to note that since 1917, from the date of Bolsheviks rise to power in Russia, to 1991, rise to power of the current political force, elite, passed 74 years. One may object also, insisting on 1989, when the power monopoly of the CPSU fell.  Then we get 72 years as well. One may speak about that there are events, which our consciousness associates with arrival of new elite, loss of power by one elite and its interception by the other one. But there are real changes taking place  under the influence of cumulative causes, i.e. large total of micro-causes.   In the historical process there is a lot of eventual, which amend effects of cumulative causes.  And the peaks of solar activity rare repeatedly occur every 12 years (plus or minus 1-3 years).</p>
<p>At an average, every 72 years the power from the third generation elite goes on to the first generation elite under the influence of internal causes. Wars, revolutions, external causes may deform these processes.  Then, the new cycle “is linked to” the next cycle of solar activity, but 72-year-period surprisingly insistently proves itself in the cyclic march of history.</p>
<p>Based on this, 2 peaks of solar activity fall upon the first generation elite, two ones upon the secomd generation elite and two ones upon the third generation elite. It makes 72 years. As to the change of voluntary helpers to domain experts, according to our conception, thesе are not simply domain experts, but special ones — resonators, it coincides with 24-year-cycle. But the business domination of the individuals having traits of hysteroidity may simply not take place. They are often slept away by severe competition, especially if nearby there is a big, developed country.  Businesses under the direction of psychopathic, hysteroid persons go simply bankrupt due to these unfavourable external causes. This explains also the fact that Kondratyev cycles are in some way different, than 72-year-cycles.  But in any of its interpretations it is at least 48 years.</p>
<p>The moment of increased solar activity is not change of psychotype power at its maximum. This is a peculiar index of transition of cumulative forces from the support of one psychotype to the blocking of its development. But these changes themselves go step by step, slowly and cumulatively. Simply all of a sudden everybody begins to be aware of that something in the system of socioeconomic relations went not in a way as required. Perceived contradictions begin to grow, the power built on deter mined psychologic grounds collapses and the other one emerges.</p>
<p>As applied to resonators. They exist in any period of social and economic development. But there comes their turn to be leading in the new spiral of social and economic development. They begin to understand this more often themselves and feel strength for a shoot forward in their activity (if they are able to detect the influence of cumulative causes). And after their peak of solar activity this process steps up. Psychophysiologic causes of this are clear.  In the period of solar activity the mechanism of nervous reflex make-and-brake and change of stereotypes of our thinking functions better. And the resonators themselves, and what is important  — the neighborhood  -  begin to understand abilities of different groups of population, their own abilities, to understand, whom it is best of all to rely on. This is advantageous for everybody.</p>
<p>But here comes the new peak of solar activity. Once again, the stereotypes of thinking begin to change actively. And gradually, gather cumulatively the persons, who understand that the resonator efforts may be improved by activization  of external contacts, not by way of quest for the new, but through reproduction of the specimen working already good. At the next peak of solar activity this process speeds up. This is the first peak of solar activity for postresonators. At the second peak of solar activity you begin to feel that something goes not so that you want.</p>
<p>And much as postresonators rise to power, postpostresonators succeed to them. Or the economy of the given country is captured by economically active subjects of other countries, goes bankrupt through competition with them. Sometimes such competition is blocked, inclusive of adoption of laws (in 1933 in the USA), introducing duties against imported goods, and sometimes just physically (“Boston Tea Party” etc.).  This happens more often in the countries, which are leading in the politico-military contezt.</p>
<p>From time to time, elite in this or that state is like appointed by the government  of another, more powerful state. The cycle will be also different, than 72 years.</p>
<p>But in general, if to speak about action of external causes, 72 years pass in all, and once again the new generation elite appears on historical stage. However, the moment of power transition from the third generation elite to this one of the first generation is usually hysterical, and often has bloody tones. Especially when it happens during specific activity of pospostresonators.  Hystericality of postpostresonators’ manifestation is diversified. One of such manifestations is an active actuation of protective responses.  Rational arguments are rejected by passion, violence, veiled by denunciation of other people...</p>
<p>But have there been more such psychoeconomical crises?  There is reason to believe that as such was a depression, and according to some authors, a crisis also of  1873-1896 etc.  US economists have a little bit different point of view concerning limits of the given depression -  from 1873 to 1879. But this is more internal cause for Germanyt. As for the USA, it had already the signs of external one.    The single-type psychoeconomic associations with the crisis of 1929-1933 manifested here. Prior to the panic on the Stock Exchange in 1873 , there were inflation of bubbles at realty markets, land markets,  avalanche-like reduction of share costs etc.  But the main prove that psychotypes of economically active population after a long period had trend of appearance of increasing number of resonators – change of the rates of economic development of the country. Germany becomes the leader of the industrial growth.  Average annual increase in industrial products in 1891 – 1913 made in England  - 2.1%,   USA – 4,12%, Germany – 4,2%. That is the economic development cycles established by internal causes may be different in various  countries and may not coincide.</p>
<p>It is surprising, but the described cycles coincide with periods, cycles of mankind development which are resulted  in the Volos Book (Vedic religion).</p>
<p>In the Vedic calendar there are sacred figures, including   144.  In the Vedic periodiztion there is a cycle called the Circle of Life. It has duration of 144 years. If based on this reference, 72 years make a half of the Circle of Life. It is not improbable that systematic changes ib the human psychology lie in 144-year-cycle, which is also associated with the cycles of solar activity.</p>
<p>Let’s note that according to Mayan calendar (December 21) and Vedic calendar in 2012 the new era comes —Water Bearer’s Epoch, which replace Fishes’ Epoch.  During the epoch change, new law objectives of mutual relations of psychotypes will manifest. Deduct 144 years from 2012. We get 1868.  We may nominally adopt it as a being commenced cycle of social changes in the USA.  Having selected in the Internet the combination of 1868 and USA», we receive the answer.</p>
<p>Presidential election in the USA in 1868 were the first after the civil war, in which with giving voting right to former blacky slaves the general Grant  swept the election.   The same year, amendment to the US Constitution, which guarantees the US citizenship to all persons, who were born in its territory. There is something to reflect about, knowing the birth place of US President Obama and polemics in this respect.</p>
<p>But we need the resulted estimations more for a psychologic, intuitive, sacral prompting message on the most important year in breaking the crisis of 1929-1933.  We get 1940.</p>
<p>In order to prove the reasons of such conclusion, we will refer to the US Unemployment Curve</p>
<img src="../Images/Fragments/a12p1.png" alt="Unemployment in the USA" />
<p><b>Unemployment in the USA from 1910 to 1960 and the Great Depression years (1929—1939) are highlighted</b><br />
<a href="http://upload.wikimedia.org/wikipedia/commons/5/58/US_Unemployment_1910-1960.gif">http://upload.wikimedia.org/wikipedia/commons/5/58/US_Unemployment_1910-1960.gif</a></p>
<p>Total number of unemployed in 1933 reached 17 mln. people, which made the fourth part of all labour force in the country. How can on consider this year as the one of crisis’ termination?</p>
<p>And in 1939 qualitative reorganizations were launched in the US economy and precritical level of industrial production was reached.  Though, the American economists say better about this. “The government policy adopted after the Great Depression engendered a new economic order...  In wartime, the government expenditures reached an all-time high. The country enabled all its production capacities and enlisted the services of practically all Americans of working age. And though most capacities were directed on satisfaction of wants of military nature, the total output met the society’s needs. By the end of the war, the majority of survived Americans were in more favourable condition, than before the war, and the Great Depression, without doubt, was over.”  (see: [1], pages 28-29).</p>
<p>These words have a deep meaning. What is full employment of population, full workload of industry? This is the time, when resonators, domain experts are in the spotlight, everything depends on them. Before, much, if not all, depended on “wheedling” of orders, on the system of realization of produced goods (“voluntary helpers” do that), on preferences on the part of the state (“voluntary helpers” wheedle them also) etc.  In wartime, in the period of full employment and guaranty of almost automatical sale of the products, the professional skill of those, who can fabricate, professionals-domain experts, comes to the fore.</p>
<p>Such periodization of the Great Depression coincides with opinion of many leading American economists of today: years from 1929 to 1939. This is important, since in the event of recognition of analogy between the Great Depression and today’s processes in the economy,   it is easier psychologically and more precisely from scientific point of view to approach to designation of a date of termination of the recession commenced in 2008(?).</p>
<p>Therefore, the crisis, which it is commonly supposed to designate as the crisis of 1929-1933, lasted in fact until the outbreak of the World War II.  For the USA this is a crisis in the system of socioeconomic relations, which usually precedes the resonators’ rising to power.</p>
<p>It is similar to the crisis in Rome under Neron’s rule, it is similar to the crisis in the USSR in the early 1990s, it is similar to hundreds of such crises, which took, are still taking and will take place in history during appearance of the third generation elite, in combination with enrichment of individual hysteroid traits in workers, in economically active population, and in case of impossibility of overcoming by it of the system of socioeconomic contradictions using understanding of the essence of the event and anticipatory decision-making... Protective responses of elite and persons imitating it become an obstacle on the way of conscious reorganizations. It is also dramatized by the fact that the third generation elite leaving the historical scene is not able to change its psychotype according to the current situations, intercept the leadership from resonators or simply from reasonable persons.</p>
<p>This is one of the reasons of that the successful elite should know how to change its psychotype  vibrationally against the opposite,. It is required in order to follow vibrational changes of the population psychotype and successfully guide it both using psychological mechanisms and leading by personal example, but not only using intelligent decisions or military force. Because, when the elite psychotype does not “engage” this one of the gross of the people, the elite is just thrown over. Naturally, this process is preceded by the process of losing by elite its usefulness for people and control over surplus product and financial flows.</p>
<p>In the crises of such kind the role of hysteroid personalities is sharply enhanced. This is manifested in many aspects.</p>
<p>First, in the change of conative basis of decision-making in key subjects of  economic activity (excluding resonators). Motives of economic behaviour become more temporary.  In them, the role and significance of emotional component are enhanced. Irrational component in the motivation grows.</p>
<p>Second, by enhancement of the role of protective responses during decision-making. The people, in a lesser degree, than usually, begin to obey to arguments of  impersonal reflection, but to emotional moments, impulses of the unconscious.</p>
<p>Third, by aggravation of contradictions between the conscious and unconscious, which makes human behaviour alogical and complicates their control using means, which normally provide quite good effect in a calm situation.   This is like in a stressful situation — it is not clear, what will be specific response of people. Herefrom, beyond the scope of the given crisis, from the point of view of today, the estimation of the actions taken may radically differ from the estimation of such actions by the participants of the given process.</p>
<p>Fourth, guiding the people logically requires emotional interjection, psychotherapeutic approaches on a national scale. In this respect, the managerial decisions and behaviour of F.Roosevelt in the period of crisis do not seem as something alogical. He was forced to guide hysterical people using appropriate methods.</p>
<p>F.Roosevelt was in the situation, when the coming out of the crisis must be without rely on reasonable elite. This fact, which was recognized by F.Roosevelt himself, when he directly addressed the nation and accused his Washington advisors of their incompetence. But this is recognized by his opponents also describing the atmosphere, which has formed in the government agencies and F.Roosevelt’s entourage.  Whether was it possible to do anything with hysterical elite?  But F.Roosevelt did as near as maximum, what he could do. He prevented the bloodshed, which accompanied the change of the third generation elite before. But he could not prohibit the elite from taking unreflective decisions sometimes. So, destruction of food products at the moment, when there were hungry people, this was distinctly alogical step directed against ordinary Americans, but protecting interests of large wholesalers and banks, which credited them. And F.Roosevelt tells straight about it.</p>
<p>The elite did everything in a manner, how the third generation elite had done centuries ago before that. It did not change its psychotype, did not increased production efficiency, but increased the exploitation of its subjects. And the decision on destruction of food products was taken by elite.    This decision came not in the period of F.Roosevelt rising to power, but under H.Hoover. However, F.Roosevelt could not do anything with it. Though he did the main thing — he prevented the bloodshed and created conditions for a gradual transition of power to a new elite. Of course, the war “helped” it.  In the outbreak of recession of 1929-1933 the power was in hands of elite, FRS, bankers and wholesaler. This power remained in their hands after the crisis also, but more realistic people came to power. And a part of elite managed to become more realistic after the events had happened. Some part of elite is able to change its psychotype. And during the period after WWII the first generation elite guided already the USA.</p>
<p>Therefore, the events of 1929 — 1939 may serve as source of our khowledge on human behaviour in the crisis time. F.Roosevelt’s decisions at a given instant had not only, and maybe even not so much economical, as psychological and even psychiatrical character.   The crisis itself, depression, if to be based on objective parameters, lasted in the USA from 1929 to 1939.</p>
<p>So far in the history of mankind the psychoeconomical crises emerged and were surmounted spontaneously, due to internal causes. And it was always associated with stress factors.</p>
<p>Today there are required scientific backgrounds for more supraliminal role of regulators in the overcoming psychoeconomical crises.</p>
<p>Let’d draw conclusions.</p>
<p>Psychotypes of elite, economically and politically active population change cyclically. Changed psychotypes in elite, economically and politically active population bring in not only the different character features into the system of  socioeconomic relations, but they bring in a different motivation system, values, different demands, different culture. These are changed motives of behaviour   which direct key participants of the socioeconomic process, key subjects of economic activity on achievement of other values, than it was before. During domination of the values of hysteroid type in the society they direct their efforts on self-affirmation through possession of new, large and prestigious buildings, jim-dandy cars and grooves... They enjoy their prestigious situation itself, their private aircrafts, yachts, special expensive watches, tennis-courts etc and so on, Tis list is endless. And what is important. This endless list of actualized demands of hysteroids, postpostresonators was added at the present moment also by share ownership, stock market game, money on accounts in unlimited amounts — the more money, the more prestigious.  In  these values people fall somehow into the shade. This is a feature of individuals with traits of hysteroidity, demand for a self-manifestation, My Very Self metaprogramme are the most expressed in them,.  These values are combined with less expressed organizational abilities. Demand for ownership of endless list of prestigious things, but what is more important — signs of prestige, such as ownership of shares of large companies, which change their value much hieroglyphically and emotionally — there is something to speak in the most distinguished parlours – forms endless demand  for money. And as always in the history, this psychotype and all its imitators begin not to get this money through a back-breaking managerial work, but to “carve out” in everyone, who falls for. It is easier to ”trim” those, who stands below in the prestige stairway according to his/her professional and social position. These are their incomes that are coming down during domination of postpostresonators. Social stratification in the society becomes bigger. And even if the government, regulators, seeing a prerevolutional situation, find out the funds and invest them to support pants of people,  — they accumulate this money in various ways, sometimes in sophisticated and clever ones, in the circulation of the values dominant in the society.     Therefore, cyclically along with the psychotype change in elite,  the degree of social stratification is changing also.</p>
<p>Economical objective laws in the society, where the values of hysteroid type reign supreme,  become different, than they were decades ago. The economical laws discovered at some stage of social evolution are transformed along with the change in people.</p>
<p>There is reason to believe that the knowledge the causes of psychoeconomical crises occurence enhances the ability to control this process in a larger degree, than it was before. In its total, the crisis bailout plan should include also measures on changing psychotypes of economically active population and elite.</p>
<br />
<p>Robert B. Reich, Aftershock. The Next Economy - М., Karriera Press, 2012. – page193.<br />
N.I.Konyukhov, O.N.Arkhipova, E.N.Konyoukhova. Psychoeconomy. - М.: 2-nd edition, 2012 -  540 pages.</p>
<p>For scientific discussions please write to Konuhov1@mail.ru</p>
        </div>
    </div>
</asp:Content>
